title: ChemLog
author:
  name: Alpyne
  email: alpyne.dreams@gmail.com
description: Track your drug, reaserach chemical, nootropic, and substance use.
remote_theme: jekyll/minima
show_excerpts: true
minima:
  skin: dark
  social_links:
    github: AlpyneDreams/ChemLog
